In [1]:
import numpy as np

matriu = np.random.randint(1, 36, [5,5])
print(matriu)


            

print('Es Divisible per 4?')
print(matriu % 4 == 0)
print('Valors exactes després de dividir per 4:')
print(matriu / 4)

[[14  6 33 35 14]
 [19 22  7 32 35]
 [ 1 19 31 19 29]
 [ 5 19 17  4  3]
 [30 24  6 17  3]]
Es Divisible per 4?
[[False False False False False]
 [False False False  True False]
 [False False False False False]
 [False False False  True False]
 [False  True False False False]]
Valors exactes després de dividir per 4:
[[3.5  1.5  8.25 8.75 3.5 ]
 [4.75 5.5  1.75 8.   8.75]
 [0.25 4.75 7.75 4.75 7.25]
 [1.25 4.75 4.25 1.   0.75]
 [7.5  6.   1.5  4.25 0.75]]
