In [1]:
import numpy as np

matriu = np.random.randint(1, 25, [5,5])
print(matriu)

while True:
    x = input('Escriu el número de fila entre 0 i 4:')
    y = input('Escriu el número de columna entre 0 i 4:')
    try:
        x = int(x)
        y = int(y)
    except:
        pass
    else: 
        if 0 <= x <= 4 and 0 <= y <= 4:
            break
            
fila = matriu[x,:]
col = matriu[:,y]
print('Elements fila:', x, 'són', fila)
print('Elements Columna:', y, 'són', col)
fc = np.stack((fila,col))
print(fc)
total = np.sum(fc)

print('La suma total fila i culumna és', total-fc[0,y])

[[11 13  5 14 24]
 [15 13  6 19  6]
 [19 18 10  7 20]
 [ 2 11 15 15  2]
 [ 2 20 13  2  2]]
Escriu el número de fila entre 0 i 4:0
Escriu el número de columna entre 0 i 4:5
Escriu el número de fila entre 0 i 4:0
Escriu el número de columna entre 0 i 4:3
Elements fila: 0 són [11 13  5 14 24]
Elements Columna: 3 són [14 19  7 15  2]
[[11 13  5 14 24]
 [14 19  7 15  2]]
La suma total fila i culumna és 110
