In [1]:
import numpy as np

matriu = np.random.randint(1, 25, [5,5])

print(matriu)

v_max = np.amax(matriu)
print('El valor màxim de la matriu és: ',v_max)
fila = np.amax(matriu, axis=1)
col = np.amax(matriu, axis=0)

print('El valor màxim de cada fila és: ', fila)
print('El valor màxim de cada columna és: ', col)

[[17 16  5 14  5]
 [ 4  2 15 20  4]
 [ 9 23  2  9  1]
 [16 14  9 13 14]
 [15  3  2 23 22]]
El valor màxim de la matriu és:  23
El valor màxim de cada fila és:  [17 20 23 16 23]
El valor màxim de cada columna és:  [17 23 15 23 22]
