In [1]:
import numpy as np

matriu1 = np.random.randint(1, 15, [2,2])
matriu2 = np.random.randint(1, 15, [3,3])
matriu3 = np.random.randint(1, 15, [4,4])

print(matriu1)
print(matriu2)
print(matriu3)
print(matriu1 + matriu1)
print(matriu1 + matriu2)
print(matriu1 + matriu3)



[[9 4]
 [7 1]]
[[ 4 10 14]
 [13 14  6]
 [14  4  6]]
[[ 3  2  7  2]
 [ 2  4  9 10]
 [ 2  8  5  1]
 [ 1  2  1  4]]
[[18  8]
 [14  2]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 