In [5]:
import numpy as np

matriu = np.random.randint(1, 36, [5,5])
print(matriu)


            

print('Es Divisible per 4?')
mask = matriu % 4 == 0
print(mask)
print('Valors exactes després de dividir per 4:')
print(matriu / 4)
print('Valors aplicant máscara')
print(matriu[mask])

[[24 32 13 22  4]
 [12 35 33 32 27]
 [35 18 28 28 27]
 [32  4  9  2 35]
 [ 7 15 17 23 10]]
Es Divisible per 4?
[[ True  True False False  True]
 [ True False False  True False]
 [False False  True  True False]
 [ True  True False False False]
 [False False False False False]]
Valors exactes després de dividir per 4:
[[6.   8.   3.25 5.5  1.  ]
 [3.   8.75 8.25 8.   6.75]
 [8.75 4.5  7.   7.   6.75]
 [8.   1.   2.25 0.5  8.75]
 [1.75 3.75 4.25 5.75 2.5 ]]
Valors aplicant máscara
[24 32  4 12 32 28 28 32  4]
