In [1]:
import numpy as np

x = input('Escriu el número de fila entre 0 i 15:')
y = input('Escriu el número de columna entre 0 i 15:')

while True:
    try:
        x = int(x)
        y = int(y)
    except:
        pass
    else: 
        if 0 <= x <= 14 and 0 <= y <= 14:
            break
            
matriu = np.random.randint(1, 25, [x,y])
print(matriu)  


sumcol=np.apply_along_axis(sum,0,matriu)
print('La suma de les columnes és:', sumcol)    

sumfila=np.apply_along_axis(sum,1,matriu)
print('La suma de les files és:', sumfila)



Escriu el número de fila entre 0 i 15:5
Escriu el número de columna entre 0 i 15:5
[[19 24 16  2 21]
 [22 21 10 23  5]
 [21 18 12 11 21]
 [22 21  4 17  9]
 [21  2  1  3 19]]
La suma de les columnes és: [105  86  43  56  75]
La suma de les files és: [82 81 83 73 46]
