In [1]:
import numpy as np


while True:
    x = input('Escriu el número de fila i columna entre 0 i 20:')
    try:
        x = int(x)
    except:
        pass
    else: 
        if 0 <= x <= 19:
            break
            
matriu = np.random.randint(0, 100, [x,x])
print(matriu)


Escriu el número de fila i columna entre 0 i 20:99
Escriu el número de fila i columna entre 0 i 20:11
[[87 18 45 40 50 75 18 18  3 59 64]
 [50  4 72 94 97 72 19 87 24 38 51]
 [36 98 49 66  6  2 62  6 36 54 40]
 [77 71 17 96 65  2 82 79 13 24 14]
 [ 2 19 85 98 19 96 80  9 94 18 13]
 [30 49  7 68 80 83 14 76 41 74 56]
 [37  5 81 33 13 56 15 60 58 79 15]
 [61 68 88 10 12 23 32 42 80 74 82]
 [30 97 88 69 68 31 76 94 32 28 24]
 [21 97 89 92 25 81 46 71 59 44 85]
 [73  6 81 68 67 75 43 68 50 76  6]]
